create table CSV_TARGET
(
    I_YEAR               CHARACTER VARYING,
    INDUSTRY_AGGREGATION CHARACTER VARYING,
    INDUSTRY_CODE        CHARACTER VARYING,
    INDUSTRY_NAME        CHARACTER VARYING,
    UNITS                CHARACTER VARYING,
    VARIABLE_CODE        CHARACTER VARYING,
    VARIABLE_NAME        CHARACTER VARYING,
    VARIABLE_CATEGORY    CHARACTER VARYING,
    I_VALUE              CHARACTER VARYING,
    INDUSTRY_CODE2       CHARACTER VARYING
);

